language: java
jdk:
 - oraclejdk8
 - openjdk8
dist: trusty
addons:
  sonarcloud:
    organization: "sese-xp3-ws2017"

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
 - mvn clean test jacoco:report coveralls:report
notifications:
   slack: sese-xp3-ws2017:ZsrYv58SOlXQoFtiHS29Qlt0