# Set server port via command line parameter --port
# otherwise defaults to a random port
server:
  port: ${port:0}

spring:
  thymeleaf:
    # Disable thymeleaf cache to enable live refresh for rapid development (template hotswap)
    cache: false
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static/
    cache-period: 0
  jpa:
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: search_indicies
          analyzer: at.ac.tuwien.student.sese2017.xp.hotelmanagement.search.analyzer.EntityAnalyzer
        hbm2ddl:
          auto: create-drop

# Hotel management app configuration
appconfig:
  injecttestdata: ${testdata:true} # TODO set to false as soon as heroku deploy is configured correctly
